properties:
  configurationVersion: 0.2.0
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Canva Affinity 3
      settings:
        id: Canva.Affinity
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Bruno
      settings:
        id: Bruno.Bruno
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install K-Lite Codec Pack Mega
      settings:
        id: CodecGuide.K-LiteCodecPack.Mega
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure AzCopy
      settings:
        id: Microsoft.Azure.AZCopy.10
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure Functions Core Tools
      settings:
        id: Microsoft.Azure.FunctionsCoreTools
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure Storage Emulator
      settings:
        id: Microsoft.Azure.StorageEmulator
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure Storage Explorer
      settings:
        id: Microsoft.Azure.StorageExplorer
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Azure CLI
      settings:
        id: Microsoft.AzureCLI
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install WhatsApp Beta
      settings:
        id: 9NBDXK71NK08
        source: msstore
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install CLR Types for SQL Server 2019
      settings:
        id: Microsoft.CLRTypesSQLServer.2019
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Apple Music
      settings:
        id: 9PFHDD62MXS1
        source: msstore
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Edge Dev
      settings:
        id: Microsoft.Edge.Dev
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Adobe Acrobat Reader 64-bit
      settings:
        id: Adobe.Acrobat.Reader.64-bit
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install 1Password
      settings:
        id: AgileBits.1Password
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft ODBC Driver 17 for SQL Server
      settings:
        id: Microsoft.msodbcsql.17
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Power Automate Desktop
      settings:
        id: Microsoft.PowerAutomateDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Remote Help
      settings:
        id: Microsoft.RemoteHelp
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install SQL Server Management Studio
      settings:
        id: Microsoft.SQLServerManagementStudio
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Teams
      settings:
        id: Microsoft.Teams
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install WizTree
      settings:
        id: AntibodySoftware.WizTree
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Ubuntu
      settings:
        id: Canonical.Ubuntu
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install DB Browser for SQLite
      settings:
        id: DBBrowserForSQLite.DBBrowserForSQLite
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install EarTrumpet
      settings:
        id: File-New-Project.EarTrumpet
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Mp3tag
      settings:
        id: FlorianHeidenreich.Mp3tag
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Web Deploy
      settings:
        id: Microsoft.WebDeploy
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git Credential Manager
      settings:
        id: Git.GCM
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Windows App
      settings:
        id: Microsoft.WindowsApp
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install GitHub Desktop
      settings:
        id: GitHub.GitHubDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git LFS
      settings:
        id: GitHub.GitLFS
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Dual Monitor Tools
      settings:
        id: GNE.DualMonitorTools
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Google Chrome
      settings:
        id: Google.Chrome
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Google Quick Share
      settings:
        id: Google.QuickShare
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Cyberduck
      settings:
        id: Iterate.Cyberduck
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Oh My Posh
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install mise
      settings:
        id: jdx.mise
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install FontBase
      settings:
        id: Levitsky.FontBase
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install LLVM
      settings:
        id: LLVM.LLVM
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install NanaZip
      settings:
        id: M2Team.NanaZip
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install UniGetUI
      settings:
        id: MartiCliment.UniGetUI
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft App Installer
      settings:
        id: Microsoft.AppInstaller
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Edge
      settings:
        id: Microsoft.Edge
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft Edge Beta
      settings:
        id: Microsoft.Edge.Beta
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Edge WebView2 Runtime
      settings:
        id: Microsoft.EdgeWebView2Runtime
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Microsoft OneDrive
      settings:
        id: Microsoft.OneDrive
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerShell
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerToys
      settings:
        id: Microsoft.PowerToys
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Rancher Desktop
      settings:
        id: SUSE.RancherDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Windows Terminal Preview
      settings:
        id: Microsoft.WindowsTerminal.Preview
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Windows Subsystem for Linux
      settings:
        id: Microsoft.WSL
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Mozilla Firefox
      settings:
        id: Mozilla.Firefox
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Obsidian
      settings:
        id: Obsidian.Obsidian
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Spotify
      settings:
        id: Spotify.Spotify
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install VLC
      settings:
        id: VideoLAN.VLC
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install WinSCP
      settings:
        id: WinSCP.WinSCP
        source: winget
